### ISSUE TITLE
Powerline記号を含めていただきたいです

### ISSUE THREAD

**Issue by silmin** [yuru7/Firge#1]
HackGenの姉妹フォントであるFirgeを作っていただけたことに感謝します．

Firgeの

> 0 はドットゼロではなくスラッシュゼロに。
 | は破断線ではなく直線に。

の部分が特に気に入って使っています．

ただ，FirgeではHackGenのようにPowerline記号が含まれていません．

普段からPowerline記号を使っているので，是非Firgeにも対応していただけたらと思うのですが，
今後，FIrgeにPowerline記号を含めるご予定はありますか？

**Comment by yuru7** [comment]
ご意見ありがとうございます。

時期は未定ですが、FirgeでもHackGenのようにNerd Fonts対応版を用意したいと考えています。そうすればNerd Fontsに含まれるPowerline記号も含まれることになりますので、ご希望に添えるかと思います。

**Comment by silmin** [comment]
ありがとうございます！

対応予定とのことでとても嬉しいです！
対応されるまでHackGenを使いながら待ちたいと思います！

**Comment by yuru7** [comment]
Nerd Fontsを追加したFirgeNerdを作ってみました。
足早に作成したため軽く確認した程度ですが、Powerlineなど表示できるようになっています。

しばらく使ってみてからリリースには出すつもりですが、先行して利用したい場合は以下からダウンロードして使ってみてください。HackGenと同様に `FirgeNerd*` `Firge35Nerd*` がNerd Fonts追加版です。

https://github.com/yuru7/Firge/tree/v0.1.0/build

表示上の不具合など、もし気付いた点があればお知らせください。

**Comment by silmin** [comment]
ありがとうございます！
めちゃくちゃ嬉しいです！早速使ってみます！

**Comment by yuru7** [comment]
Nerd Fonts を追加した v0.1.0 をリリースしたため、こちらクローズします。

@silmin 
要望ありがとうございました🙇‍♂️
元々やろうと思っていたことではありましたが、腰が重かったので後押しとなり助かりました。

**Comment by silmin** [comment]
ありがとうございました！
