### ISSUE TITLE
Homebrew の cask-fonts への収録

### ISSUE THREAD

**Issue by hideo54** [yuru7/Firge#2]
はじめまして。素晴らしいフォントをありがとうございます。

macOS 向け package manager である “Homebrew” にはフォント用の Cask ([cask-fonts](https://github.com/Homebrew/homebrew-cask-fonts)) があるのですが、そちらに Firge を登録していただくことは可能でしょうか。もしくは、お忙しければ、私が代わりに行いますが、構いませんでしょうか。

ちなみに、HackGen は2年前にある方が追加されたようです ([PR](https://github.com/Homebrew/homebrew-cask-fonts/pull/1839))。

cask-fonts の [CONTRIBUTING.md](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/CONTRIBUTING.md) に

> We accept fonts from other sources but they must be provably popular, like JetBrains Mono and iA Fonts.

とあるのが少し心配ですが、白源が通っていることも踏まえて、とりあえず出してみたら通るのではないかと思っています。

ご検討よろしくお願いします。

**Comment by yuru7** [comment]
ご愛用ありがとうございます。

> もしくは、お忙しければ、私が代わりに行いますが、構いませんでしょうか。

はい。こちらで登録するつもりはないので、対応はお任せします。（いずれにせよMacを持っていないために検証等できないので…）

**Comment by hideo54** [comment]
かしこまりました。ありがとうございます。

**Comment by hideo54** [comment]
一応その後の報告ですが、[PR](https://github.com/Homebrew/homebrew-cask-fonts/pull/4791) を出したところお断りされてしまいました😔  ゴタゴタしただけですいませんでした…。

代わりに自分の forked repository [hideo54/homebrew-cask-fonts](https://github.com/hideo54/homebrew-cask-fonts) に登録しました。もし使いたい方がいれば
```
brew tap hideo54/cask-fonts git@github.com:hideo54/homebrew-cask-fonts.git
brew install font-firge
```
でできます。(別にしっかりメンテする気はないのでおすすめするわけではないですが)
