### ISSUE TITLE
ubuntuのNerdFontアイコンが表示されない

### ISSUE THREAD

**Issue by Rollo1h** [yuru7/Firge#4]
Firgeに一目惚れして使わせていただいております。
素晴らしいフォントをありがとうございます。

ubuntu環境のpowerlevel10kで使用したところ、[OSアイコン](https://fontawesome.com/v5.15/icons/ubuntu?style=brands)が表示されません。

FirgeNerdConsole
WindowsTerminal
ubuntu20.04 (wsl2)

<img width="230" alt="スクリーンショット 2021-09-10 051152" src="https://user-images.githubusercontent.com/42202535/132755806-d2d841a3-62e9-48f7-8bf5-55a7666bb782.png">

**Comment by yuru7** [comment]
ご報告ありがとうございます。

ご報告の通り、 `U+F31C` などの一部のグリフが含まれていなかったようです。

[v0.2.0](https://github.com/yuru7/Firge/releases) にて対処してみました。試してみてください。

**Comment by Rollo1h** [comment]
ご対応ありがとうございます。
v0.2.0にて問題が修正されていることを確認しました。
