### ISSUE TITLE
Nerd Fontsをアップデートしてほしい

### ISSUE THREAD

**Issue by Detsudetsu** [yuru7/Firge#5]
おそらくNerd Fonts V3に対応しているかどうかだと思うのですが、
Oh My PoshでUDEV GothicのNerd Font対応版では表示できているアイコンが、
Firgeでは表示できていないケースがあります。
合成元Nerd Fontsのアップデートをお願いいたします🙇‍♂

**Comment by yuru7** [comment]
お知らせありがとうございます。時間のある時に v3 を取り込んでみます。

**Comment by yuru7** [comment]
Nerd Fonts を v3.0.2 にアップデートした v0.3.0 をリリースしました。お暇なときにお試しください。

**Comment by Detsudetsu** [comment]
すみません遅くなりました🙇‍♂

Oh My Poshでアイコンが表示されるようになったことを確認しました。
Firge大好きなので本当に嬉しいです…！
ご対応ありがとうございました🙇‍♂
